"""Requirements Validation using CodeAct - Phase 1 Implementation.

NOTE: This implementation uses executable code generation to match requirements
against implementation. The matching algorithm generated by the LLM may use:
- Simple string matching
- Keyword extraction
- Pattern matching

For production use, consider enhancing with:
- Fuzzy string matching (e.g., difflib.SequenceMatcher, fuzzywuzzy)
- Semantic similarity (e.g., sentence transformers)
- Synonym handling
- Domain-specific dictionaries

The current approach prioritizes transparency (executable code visible)
over sophisticated NLP techniques.
"""

import logging
from typing import Dict, Any
from ..codeact.agent import CodeActAgent
from ..codeact.sandbox import CodeSandbox

logger = logging.getLogger(__name__)


class RequirementsValidatorCodeAct:
    """
    Validate PR implementation against documented requirements using executable code.

    Solves the "3/4 vs 4/4" problem:
    - Detects if developer implemented 3 features when 4 were required
    - Detects if developer implemented 5 features (scope creep)
    - Provides precise counts and missing/extra features
    """

    def __init__(self, sandbox: CodeSandbox = None, max_retries: int = 3):
        """
        Initialize requirements validator.

        Args:
            sandbox: CodeSandbox instance (default: creates new)
            max_retries: Maximum retry attempts for code execution
        """
        self.agent = CodeActAgent(sandbox=sandbox, max_retries=max_retries)

    def validate(
        self,
        requirements_text: str,
        code_changes: str,
        pr_description: str = "",
    ) -> Dict[str, Any]:
        """
        Validate implementation vs requirements.

        Args:
            requirements_text: Requirements from README, REQUIREMENTS.md, etc.
            code_changes: PR code changes (diff or full content)
            pr_description: PR description (optional)

        Returns:
            dict with:
                - success: bool
                - required_count: int
                - implemented_count: int
                - missing_features: List[str]
                - extra_features: List[str]
                - status: "COMPLETE" | "INCOMPLETE" | "SCOPE_CREEP"
                - scope_alignment: "EXACT" | "MISSING" | "EXTRA"
        """
        task = """
Match requirements against code implementations using helper functions.

AVAILABLE HELPERS (already imported):
- extract_requirements_list(text) -> List[str]
- extract_function_names(code) -> List[str]
- keyword_match(requirement, func_name) -> bool

Write Python code that:
1. Gets requirements and code from context dict
2. Calls the helper functions to extract requirements and function names
3. Loops through requirements and matches them to functions using keyword_match()
4. Builds result dict with counts, missing features, status

Example structure:
requirements_text = context.get('requirements', '')
code_text = context.get('code_changes', '')

requirements = extract_requirements_list(requirements_text)
functions = extract_function_names(code_text)

debug_matches = []
implemented = []
missing = []
for req in requirements:
    found = False
    for func in functions:
        matches = keyword_match(req, func)
        debug_matches.append({'req': req, 'func': func, 'matched': matches})
        if matches:
            implemented.append(req)
            found = True
            break
    if not found:
        missing.append(req)

result = {
    'required_count': len(requirements),
    'implemented_count': len(implemented),
    'missing_features': missing,
    'extra_features': [],
    'status': 'COMPLETE' if len(implemented) == len(requirements) else 'INCOMPLETE',
    'scope_alignment': 'EXACT' if len(implemented) == len(requirements) else 'MISSING',
    'debug_data': {
        'requirements_text_len': len(requirements_text),
        'code_text_len': len(code_text),
        'code_text_preview': code_text[:200],  # First 200 chars
        'requirements_found': requirements,
        'functions_found': functions,
        'matches': debug_matches[:20]  # Limit matches to first 20
    }
}
"""

        result = self.agent.forward(
            task=task,
            code_changes=code_changes,
            context={
                "requirements": requirements_text,
                "pr_description": pr_description,
            },
        )

        if not result["success"]:
            logger.warning(f"Requirements validation failed: {result.get('error')}")
            # Fallback to basic analysis
            return {
                "success": False,
                "error": result.get("error"),
                "fallback": True,
            }

        # Ensure result has the expected structure with defaults
        analysis = result.get('result') or {}
        logger.info(f"Raw analysis result: {analysis}")

        # Add defaults for missing fields
        if not isinstance(analysis, dict):
            analysis = {}

        return {
            "success": True,
            "required_count": analysis.get("required_count", 0),
            "implemented_count": analysis.get("implemented_count", 0),
            "missing_features": analysis.get("missing_features", []),
            "extra_features": analysis.get("extra_features", []),
            "status": analysis.get("status", "UNKNOWN"),
            "scope_alignment": analysis.get("scope_alignment", "UNKNOWN"),
            "code": result.get("code"),
            "explanation": result.get("explanation"),
            "attempts": result.get("attempts"),
        }

    def format_report(self, validation_result: Dict[str, Any]) -> str:
        """
        Format validation result as human-readable report.

        Args:
            validation_result: Result from validate()

        Returns:
            Formatted report string
        """
        if not validation_result.get("success"):
            return f"**Requirements Validation Failed**: {validation_result.get('error')}"

        report = ["## Requirements Validation Report\n"]

        # Summary
        status = validation_result.get("status", "UNKNOWN")
        req_count = validation_result.get("required_count", 0)
        impl_count = validation_result.get("implemented_count", 0)

        if status == "COMPLETE":
            report.append(f"✅ **Status**: {status}")
            report.append(f"- All {req_count} requirements implemented")
        elif status == "INCOMPLETE":
            report.append(f"⚠️ **Status**: {status}")
            report.append(
                f"- Implemented {impl_count}/{req_count} requirements"
            )
        elif status == "SCOPE_CREEP":
            report.append(f"⚠️ **Status**: {status}")
            report.append(
                f"- Implemented {impl_count} features but only {req_count} required"
            )

        # Missing features
        missing = validation_result.get("missing_features", [])
        if missing:
            report.append(f"\n### Missing Features ({len(missing)})")
            for feature in missing:
                report.append(f"- {feature}")

        # Extra features
        extra = validation_result.get("extra_features", [])
        if extra:
            report.append(f"\n### Extra Features ({len(extra)})")
            for feature in extra:
                report.append(f"- {feature}")

        return "\n".join(report)


# Example usage for testing
if __name__ == "__main__":
    validator = RequirementsValidatorCodeAct()

    # Test case: 3/4 implementation
    requirements = """
    ## Required Features
    1. User authentication
    2. Password reset
    3. OAuth integration
    4. Session management
    """

    code_changes = """
    def authenticate_user(email, password):
        '''Authenticate user with email and password'''
        pass

    def reset_password(email):
        '''Send password reset email'''
        pass

    def oauth_login(provider):
        '''Login via OAuth provider'''
        pass

    # Missing: Session management
    """

    result = validator.validate(requirements, code_changes)
    print(validator.format_report(result))
